<a href="https://colab.research.google.com/github/DikshaDayal/Machine-Learning/blob/main/3.1.%20Numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy :- Numerical Python

Advantages of Numpy Arrays:-
1. Allow several Mathematical Operations
2. Fastest operations

In [1]:
import numpy as np

List Vs Numpy

In [2]:
from time import process_time

Time taken by a list

In [3]:
Python_list = [i for i in range(10000)]

start_time = process_time()

Python_list =  [i+5 for i in Python_list]

end_time = process_time()

print(end_time - start_time)

0.0017175370000002133


In [9]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0012873209999995083


Numpy Arrays

In [10]:
#List
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [12]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Creating a One Dimensional array

In [13]:
#creating a one dimensional Array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [15]:
a.shape  # Number of rows and columns

(4,)

In [17]:
#2-D Array
b = np.array([(1,2,3),(3,2,1)])
print(b)

[[1 2 3]
 [3 2 1]]


In [18]:
b.shape

(2, 3)

In [19]:
c = np.array([(1,2,3,4),(5,6,7,8)] , dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


 Initial placeholders in numpy array

In [20]:
#create a numpy of zero
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
#create a numpy of ones
y = np.ones((4,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
#array of a particular value
z = np.full((3,3),5)
print(z)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [26]:
#create an Identity matrix
w = np.eye(4)
print(w)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [27]:
#create a numpy arrays with random value
b = np.random.random((3,4))
print(b)

[[0.3019739  0.9162968  0.95740068 0.06605905]
 [0.99193202 0.65213267 0.61389349 0.22057369]
 [0.56052091 0.19935479 0.928833   0.87909306]]


In [29]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[43 35 48 12 33]
 [57 24 35 37 75]
 [53 99 60 88 21]]


In [35]:
# array of eveenly spaced values
# (first two value represents the range and the third number reprenting the number of elements)
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [36]:
# Here we are specifying the step size of it
d = np.arange(10,30,2)
print(d)

[10 12 14 16 18 20 22 24 26 28]


In [39]:
# convert a list to an array
list2 = [1,2,3,4,5]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Analysing a Numpy Array

In [40]:
c = np.random.randint(10,100,(5,5))
print(c)

[[55 61 32 36 65]
 [87 88 32 20 29]
 [45 63 22 48 85]
 [37 71 88 65 98]
 [73 55 61 87 84]]


In [41]:
#array Dimensions
print(c.shape)

(5, 5)


In [42]:
#Number Of dimensions
print(c.ndim)

2


In [43]:
#Number of Elements in the array
print(c.size)

25


In [44]:
#Checking the daa type of the values inn the array
print(c.dtype)

int64


Mathematical Operations on a np array

In [45]:
list1 = [1,2,3,4,5]
list2 = [1,2,3,4,5]
print(list1+list2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [49]:
a = np.random.randint(1,5,(3,3))
print('a = ' ,a)
b = np.random.randint(1,5,(3,3))
print('b = ' , b)

a =  [[2 4 2]
 [2 4 4]
 [4 1 2]]
b =  [[3 3 1]
 [4 3 3]
 [3 4 2]]


In [52]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

# OR
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))



[[5 7 3]
 [6 7 7]
 [7 5 4]]
[[-1  1  1]
 [-2  1  1]
 [ 1 -3  0]]
[[ 6 12  2]
 [ 8 12 12]
 [12  4  4]]
[[0.66666667 1.33333333 2.        ]
 [0.5        1.33333333 1.33333333]
 [1.33333333 0.25       1.        ]]
[[5 7 3]
 [6 7 7]
 [7 5 4]]
[[-1  1  1]
 [-2  1  1]
 [ 1 -3  0]]
[[ 6 12  2]
 [ 8 12 12]
 [12  4  4]]
[[0.66666667 1.33333333 2.        ]
 [0.5        1.33333333 1.33333333]
 [1.33333333 0.25       1.        ]]


In [56]:
print(a)
print(np.transpose(a))

[[2 4 2]
 [2 4 4]
 [4 1 2]]
[[2 2 4]
 [4 4 1]
 [2 4 2]]


In [57]:


# reshaping a array
a = np.random.randint(0,10,(4,3))
print(a)
print(a.shape)


b = a.reshape(2,6)
print(b)
print(b.shape)


[[1 0 6]
 [1 2 1]
 [3 9 8]
 [0 2 1]]
(4, 3)
[[1 0 6 1 2 1]
 [3 9 8 0 2 1]]
(2, 6)
